### ISSUE TITLE
feat: tls 1.3 compliant implementation

### ISSUE THREAD

**Issue by viztea** [melike2d/kuikku#1]
QUIC embeds the TLS 1.3 handshake protocol for improved security and fewer round-trips  

## Resources

**RFCs:**
- [Using TLS to Secure QUIC](https://www.rfc-editor.org/rfc/rfc9001.html)
- [TLS 1.3](https://www.rfc-editor.org/rfc/rfc8446.html)

**Implementations:**
- [**pjtr/agent15**](https://bitbucket.org/pjtr/agent15)
- [**rmarx/quicker**](https://github.com/rmarx/quicker/tree/draft-20/src/crypto) - _note: this implementation uses Draft 20 of the QUIC protocol_

## TODO:

- [x] Handshake Protocol
	- [x] Client Hello
	- [x] Server Hello
- [ ] Extensions
	- [x] (mandatory) `supported_versions`
	- [ ] (mandatory) `cookie`
 	- [x] (mandatory) `signture_algorithms`
 	- [ ] (mandatory) `signature_algorithms_cert`
  	- [x] (mandatory) `supported_groups`
	- [x] (mandatory) `key_share` 
 	- [x] (mandatory) `sever_name`
 	- [x] `application_layer_protocol_negotiation`
	- [ ] `certificate_authorities`
	- [x] `psk_key_exchange_modes`
- [ ] Cryptography
	- [ ] Cipher Suites
		- [ ] (mandatory) `TLS_AES_128_GCM_SHA256`
 			- [ ] jvm
			- [ ] linux
		- [ ] (should) `TLS_AES_256_GCM_SHA384`
 			- [ ] jvm
			- [ ] linux
		- [ ] (should) `TLS_CHACHA20_POLY1305_SHA256`
 			- [ ] jvm
			- [ ] linux
	- [ ] Signature Algorithms
		- [ ] `rsa_pkcs1_sha256` (must for certificates)
			- [x] jvm
			- [ ] linux
		- [ ] `rsa_pss_rsae_sha256` (must for certificates and CertificateVerify)
 			- [x] jvm
			- [ ] linux
		- [ ] `ecdsa_secp256r1_sha256`
 			- [x] jvm
			- [ ] linux
	- [ ] Key Exchange Algorithms
		- [ ] (mandatory)`secp256r1`
 			- [x] jvm
			- [ ] linux
		- [ ] (should) `x25519`
 			- [x] jvm
			- [ ] linux
	
In order to actually implement TLS we need to have a cryptography library. The following could be used

- JVM - _could use javax crypto or bouncycastle_
- Linux X64 - _could possibly use BoringSSL or WolfSSL_

However, I'm currently working on porting Bouncycastle to Kotlin for Multiplatform cryptography. 

  Note: this todo list is a work in progress, I still need to fully research what I need for a working implementation
